### ISSUE TITLE
Uncaught ReferenceError: Template is not defined

### ISSUE THREAD

**Issue by mattiLeBlanc** [civilframe/meteor-angular-jade#13]
Hi,
since I started a new project today, based on one of a couple of months old using Angular + Meteor and Jade with packages:
mquandalle:jade
civilframe:angular-jade

I ran into the following issue while running the project:
Uncaught ReferenceError: Template is not defined

The error happens in 
```
(function(){
      Meteor.startup(function() { $('body').attr({"layout":"column"}); });
      Template.body.addContent((function() {
  var view = this;
  return HTML.Raw('<div ui-view="app" layout="column" flex="flex"></div>');
}));
      Meteor.startup(Template.body.renderToDocument);
    
}).call(this);

```

my index file is a index.jade. This used to work. No I got a bright idea and changed it to index.ng.jade.
However, then it didn't load the index.ng.jade anymore.
When  I convert my index to HTML, it works fine.

The update that I ran on my other project of a couple of months old was:
angular-meteor-data       added, version 0.0.6
angular-templates         added, version 0.0.2
angular:angular           upgraded from 1.4.7 to 1.4.8
angular:angular-animate   upgraded from 1.4.7 to 1.4.8
angular:angular-aria      upgraded from 1.4.7 to 1.4.8
angular:angular-messages  upgraded from 1.4.7 to 1.4.8
pbastowski:angular-babel  added, version 1.0.6
tomi:upload-server        upgraded from 1.3.2 to 1.3.3
urigo:angular             upgraded from 1.0.3 to 1.2.3

After update it also stopped working.

Any idea what is happening?

**Comment by pbastowski** [comment]
I would suggest to not use JADE for index.html. I used to use it with `mquandalle:jade`, but I don't any more, as there is very little benefit (plus some problems) for just the index file. Use it for all your other angular templates but not for index. This will make your life a bit easier.

Using `index.ng.jade` won't work, because `civilframe:angular-jade` writes angular templates directly into the angular templatecache. It does not output an index.html file!

**Comment by mattiLeBlanc** [comment]
Yep, ill use index.html. No big problem.
Cheers for confirming
