### ISSUE TITLE
index.ng.jade causing errors.

### ISSUE THREAD

**Issue by mackbrowne** [civilframe/meteor-angular-jade#7]
I have an index.html file with this in it: 

```html
<head>
  <title page-title></title>
  <base href="/">
</head>

<body ng-controller="MainCtrl as main" class="{{$state.current.data.specialClass}}">

<div>
  <div ui-view></div>
</div>

</body>
```

which converts to  index.ng.jade

```jade
head
  title(page-title='')
  base(href='/')
body(ng-controller='MainCtrl as main', class='{{$state.current.data.specialClass}}')
  div
    div(ui-view='')
```

I'm getting this error, and I'm unsure why.  Clearly the base is right there in the jade.

> "Uncaught Error: [$location:nobase] $location in HTML5 mode requires a <base> tag to be present!
> http://errors.angularjs.org/1.4.5/$location/nobase"

Changing index.ng.jade back to index.html seems to keep my app running, I'd really like to use 100% jade in my angular-meteor app if possible.

-Mack

**Comment by pbastowski** [comment]
@mackbrowne You can't use the `meteor-angular-jade` package for the main index.ng.jade file in your project. That is because it does not actually produce html files, as such, but rather it creates html that is converted to javascript files, which at run time load the html template(s) straight into Angular's template cache.

If you want to use JADE for your index file then you may want to consider the package `mquandalle:jade`. It works, but it is not going to understand AngularJS directly. You can overcome this to a degree, however.

**Comment by civilframe** [comment]
I concur with @pbastowski. Unfortunately, this package just doesn't support index files in Jade. Closing this.

**Comment by mackbrowne** [comment]
After doing a bit more research to how the plugin works I realize this now.

Perhaps adding something to the readme then?  I'm aware it says that only .ng.jade files will work, but I think this is still worth noting.

**Comment by civilframe** [comment]
Great suggestion. I made https://github.com/civilframe/meteor-angular-jade/issues/8 for this, and will take care of it soon.
